### ISSUE TITLE
[Bug] serde_name::trace_name does't work on structs that use #[serde(flatten)]

### ISSUE THREAD

**Issue by tsbernar** [zefchain/serde-reflection#35]
# 🐛 Bug

Adding #[serde(flatten)] makes trace_name fail to find the name.

## To reproduce

**Code snippet to reproduce**
```rust

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
struct MyStruct {
    a: u64,
    b: HashMap<String, serde_json::Value>,
}
#[derive(Serialize, Deserialize)]
struct MyStructFlat {
    a: u64,
    #[serde(flatten)]
    b: HashMap<String, serde_json::Value>,
}

assert_eq!(serde_name::trace_name::<MyStruct>(), Some("MyStruct"));
assert_eq!(serde_name::trace_name::<MyStructFlat>(), None);
```

**Stack trace/error message**
```
n/a
```

## Expected Behavior

Expected behavior is to find the struct name correctly.

## System information

**Please complete the following information:**
- 
-

**Comment by banool** [comment]
Hey @tsbernar did you manage to fix this somehow?

**Comment by tsbernar** [comment]
No, I’m still facing this issue

**Comment by ma2bd** [comment]
`serde(flatten)` is [not supported](https://github.com/zefchain/serde-reflection/tree/main/serde-reflection#unsupported-idioms).

If you work with JSON, maybe this library is closer to what you need? https://graham.cool/schemars/

**Comment by ma2bd** [comment]
@banool What change in serde 1.0.53 caused the issue?
