### ISSUE TITLE
Is Dart support still WIP?

### ISSUE THREAD

**Issue by temeddix** [zefchain/serde-reflection#48]
# 🚀 Feature Request

We have a demand of using Rust with Dart at [Rinf](https://github.com/cunarist/rinf). Is Dart support in `serde-reflection` still experimental? If it is, what can I do to make it stable?

## Motivation

**Is your feature request related to a problem? Please describe.**

It looks like Dart support has been present from a long time ago(3 years~), but it is still not marked as stable.

## Pitch

**Describe the solution you'd like**

Dart support being stable.

**Describe alternatives you've considered**

At Rinf, we are using Protobuf to send messages between Dart and Rust, but using `serde` will be much more elegant.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes

**Comment by jerel** [comment]
We are still using it (in a large project) several years later and it's feature complete in my opinion. Whether it's officially listed in the README as stable is more of an administrative and maintenance decision by the repo owner.

**Comment by ma2bd** [comment]
Great to hear from your experience @jerel.

Technically, we're actually missing something: the more comprehensive e2e tests `test_dart_{bcs,bincode}_runtime_on_supported_types` in `dart_runtime.rs`.

**Comment by ma2bd** [comment]
Just made a new task in this repo: https://github.com/zefchain/serde-reflection/issues/49

Closing this one now. We can continue the technical discussion on #49
