### ISSUE TITLE
[Bug] Enum tracing breaks for serde > 1.0.210

### ISSUE THREAD

**Issue by juntyr** [zefchain/serde-reflection#52]
https://github.com/serde-rs/serde/pull/2566#issuecomment-2438592141

TLDR: serde now includes enum variant aliases in the slice of variant names passed to `deserialize_enum` so there no longer is a 1-1 mapping from enum names to variants and the tracer tries out indices that are invalid

[sorry I'm a bit short on time right now]

**Comment by ma2bd** [comment]
In general, `serde-reflection` focuses on binary formats and can't support all of `serde` but since there's a PR, happy to review it!

**Comment by ma2bd** [comment]
Resolved in serde-reflection v0.5.0
